import { Fragment } from 'react';
import Loader from '../../../components/Loader/Loader';
import Posts from '../../../components/BlogPage/Posts';

export default function Blog({ imageSrc, title, content }) {
  return (
    <Fragment>
      <Posts
        content="Lorem ipsum dolor sit amet consectetur adipisicing elit. Impedit facilis eveniet nobis pariatur nemo, porro vero, soluta et omnis nam voluptatum officiis, voluptas dolorem veritatis minus earum laborum magnam repellendus!
        Ipsum dignissimos accusamus praesentium at voluptas eius beatae ratione dolore fuga sit. Fuga, officiis veniam tempore dignissimos magni dolor distinctio, voluptate doloribus quidem at quas explicabo consequuntur vitae aliquid eius.
        Impedit quidem eos omnis laudantium perferendis enim aliquid iste harum, obcaecati ex ad, magnam architecto optio veniam! Autem sapiente temporibus reiciendis placeat quos deleniti, nobis, omnis ab et odit tenetur.
        Esse modi voluptatibus eligendi, ullam eaque totam deserunt? Totam, corrupti ducimus? Distinctio molestiae nesciunt dicta quas perferendis ab natus ipsum magni rem modi tempora eligendi maiores, illo mollitia alias aut.
        Tempore alias laudantium expedita quas recusandae ratione velit debitis et dicta, officia deserunt fugiat ex soluta optio harum inventore, tempora in asperiores nisi provident dolorem? Voluptates accusantium iste quia quam?
        Nostrum quasi sed, minus adipisci quo inventore, pariatur iusto molestias amet ut ullam aperiam alias? Molestias dolorem magni id non. Minus eos dolorem culpa, quisquam excepturi aspernatur blanditiis iure dolorum.
        Quas doloribus saepe aperiam incidunt laboriosam sequi animi harum ullam aspernatur asperiores aliquid repellendus quis maiores corrupti beatae porro aliquam, consequatur quo molestiae et vel magni nostrum. Esse, voluptas similique.
        Perspiciatis tenetur quasi quas eveniet voluptatem quod voluptatum eligendi. Nulla alias debitis dolorum sequi, molestiae ad, ipsa veritatis rerum illum voluptates obcaecati cum iure ipsum! Impedit voluptate amet reprehenderit aliquid?
        Ipsum, ducimus esse. Est quas qui quidem molestias aliquam aliquid.   Fuga, quae consequatur? Aliquam officiis quam minima quo voluptatem dolores at, distinctio delectus, iure quos, molestias sit. Similique, nobis ut?
        Assumenda veniam dolorem excepturi accusantium nam explicabo dolores placeat optio cum. Atque, eligendi esse amet magni, velit placeat voluptate perferendis voluptatibus minima ipsum tempore necessitatibus ratione dolores saepe repellendus non.
        Consectetur aspernatur est laudantium natus repellendus, fugiat corporis ut, nesciunt aliquam inventore exercitationem ex illum quisquam voluptatibus, velit facilis molestias? Maiores autem nobis placeat consectetur suscipit harum minima perferendis ratione?
        Vel temporibus nulla voluptate id eligendi alias nihil suscipit nostrum aspernatur accusantium laboriosam consequatur, reprehenderit, labore nobis officiis inventore in. Odio nulla et in aliquam recusandae, at sequi quidem eum.
        Facilis pariatur enim ut repellendus ipsa vitae alias officia ipsam eius. Similique nam dolore itaque. Blanditiis molestias in earum, cum quam error quis atque iure tempora rem. Suscipit, fugiat eveniet.
        Sapiente nesciunt reiciendis tenetur natus, earum eligendi rem, hic quos sit similique ducimus culpa aliquid? Est, voluptates. Dolor fugiat necessitatibus quidem sequi facere tempora, aperiam voluptatum ullam eius, cumque autem?
        Ex aut perspiciatis voluptas? Possimus, aut! Quos, molestias soluta, fugit assumenda dolorum eos sit, enim tempore dicta voluptates sequi consequuntur. Maxime ipsam enim expedita tempore id sed sint in deserunt.
        Ipsam labore explicabo obcaecati a facilis pariatur consequuntur error libero aspernatur, quasi accusantium distinctio nulla minus sequi veritatis architecto, non numquam quidem totam eum dignissimos impedit. Autem voluptatem aliquam ratione.
        A necessitatibus, soluta illo animi repudiandae delectus iste commodi et doloremque? Tempora quasi ad voluptatibus porro illo incidunt. Quasi natus impedit, provident doloremque unde dolorem beatae dolor soluta cumque? Dolorum!
        Officiis saepe aperiam, obcaecati et dolorem optio, minus molestias temporibus maiores asperiores placeat incidunt praesentium ab, dignissimos eius! Id ab quae sit, veritatis tenetur repellat vitae ut! Repudiandae, reiciendis reprehenderit?
        Deleniti explicabo recusandae culpa natus, facere illo eveniet in architecto dolorem repellat minima optio nihil est praesentium laborum voluptatibus voluptatem. Dolores voluptatibus sit in eos tempora nihil molestias rerum possimus.
        Itaque harum quis unde dolor? Ab, magni sit nihil obcaecati assumenda repellat ea velit fuga, totam quo alias commodi deleniti culpa esse exercitationem est sequi hic quasi qui dolore iusto?
        Error incidunt aliquid inventore esse iste autem numquam dignissimos officia neque libero quidem soluta, ut aut ipsa quos, voluptas sapiente aperiam quisquam ea eius consequuntur minus quae. Similique, atque amet!
        Sequi porro architecto ullam cupiditate voluptatibus quae vitae dolorum rem dolores accusamus? Fugit hic aut explicabo ex doloremque! Molestiae eaque quae, quaerat quo aspernatur sapiente voluptatum fuga est sit vel.
        Aperiam natus consequuntur expedita distinctio eligendi nihil neque, et iusto sequi atque? Nemo nihil temporibus corporis laboriosam quod debitis ad consequuntur aperiam necessitatibus, doloribus eligendi, fuga quos labore? Odit, labore.
        Laborum natus veritatis sint optio, recusandae blanditiis sequi sunt velit temporibus fuga accusamus illo nesciunt repellendus voluptatem porro, exercitationem incidunt a aspernatur nihil? Assumenda veritatis sapiente consequatur illo itaque nisi.
        Corrupti perferendis molestias dignissimos commodi reiciendis sequi blanditiis, assumenda facere cupiditate ad animi explicabo distinctio eius ratione quod nisi nihil unde maxime atque tempora quam eaque consequatur, asperiores voluptas! Consectetur!
        Facere eius asperiores error consequatur, laborum molestias dolore sint voluptates expedita perspiciatis amet id doloribus aut voluptatem eaque eum cum optio quas sequi deleniti. Est sequi voluptas rem quibusdam iusto.
        Neque temporibus odit nulla itaque, cum perspiciatis! Nulla exercitationem enim laboriosam cumque, commodi saepe at adipisci facilis quos dolorem debitis magni accusamus est assumenda vitae tenetur? Quos, vitae fuga! Vitae?
        Dolores repellendus quibusdam saepe maiores animi distinctio laboriosam tempore, sequi, unde nostrum ullam quis vero accusamus quidem voluptatum totam ipsam dolorem qui ratione labore magnam provident earum commodi velit? Iste.
        Praesentium voluptatum eveniet magni facilis tenetur enim, similique veritatis ducimus esse, vero excepturi quasi placeat porro nisi eum voluptatibus atque beatae sed officia repellendus quia! Adipisci culpa libero inventore asperiores?
        Soluta rerum, facilis nostrum rem odit sapiente nihil obcaecati tenetur ad dicta alias, nisi perferendis velit quibusdam nobis, porro quia fugit adipisci repudiandae repellat. Culpa ullam reprehenderit tenetur? Eveniet, numquam?
        Praesentium expedita autem debitis! Nesciunt accusamus esse, eaque cupiditate sit quia consectetur optio in doloremque magni dignissimos veniam quis aut reiciendis fugit praesentium enim libero, beatae error quo. Quis, ipsa?
        Magni blanditiis recusandae officiis facere, beatae placeat, quidem atque explicabo provident inventore suscipit laudantium rem adipisci laborum nesciunt, autem veniam repellat cumque aut. Rem molestias, cumque deserunt ut autem aliquam.
        Incidunt placeat saepe porro! Fugiat assumenda, dicta perferendis porro quos, nemo, ex labore quasi sunt unde laudantium expedita ipsa voluptas itaque et. Esse itaque dolores, maiores beatae architecto voluptatem recusandae.
        Aspernatur ea voluptas deleniti odio, ipsa ullam eligendi culpa ex corporis facere saepe itaque fugit eos quam, nesciunt, non mollitia dicta facilis impedit praesentium illum aut soluta! Nemo, voluptatibus assumenda!
        Ducimus totam est tempore distinctio impedit, a error incidunt voluptates amet vel atque deleniti nesciunt culpa repellendus aliquid illo numquam architecto corporis dolorem harum consectetur? Asperiores pariatur quibusdam quasi blanditiis.
        Fugiat natus quam accusantium, sit magnam similique repellat quisquam perferendis perspiciatis hic atque ullam molestias. Amet ipsam illum aliquam? Reiciendis laudantium voluptatem saepe provident magni doloremque nisi incidunt nostrum. Minima.
        Dolorum reiciendis unde et delectus, rem veritatis natus mollitia iure alias consequatur, exercitationem hic, eligendi repudiandae harum. Dignissimos itaque mollitia sed vitae, voluptate ipsam sequi, laborum asperiores deleniti modi reiciendis.
        Facilis necessitatibus illo alias placeat perferendis recusandae ipsam praesentium, iure in? Facere magnam ipsam veritatis, quia culpa quaerat, quasi quisquam excepturi deleniti sapiente voluptatibus dicta voluptate suscipit in nesciunt a.
        Eligendi quasi iusto molestiae vel recusandae. Beatae deserunt laborum facere enim ad molestias sapiente ipsum expedita in? Harum voluptate, dolor reiciendis ipsum, repellendus obcaecati similique deleniti cumque est atque accusamus!
        Inventore in iusto maxime harum nisi accusantium at dicta alias! Ratione distinctio, officia consectetur fuga quod voluptatibus odit. Ex quam incidunt odio enim alias earum eos eaque necessitatibus similique possimus.
        Voluptatibus similique totam fuga, laudantium ad sed beatae vitae. Exercitationem aspernatur repellat necessitatibus magnam tenetur! Corrupti illum nobis nostrum, rem, aut dicta vel debitis animi dignissimos deleniti possimus totam odit?
        Nulla laboriosam nisi earum eaque rerum numquam enim excepturi, natus debitis quis eum iusto quasi magni distinctio consequuntur ab voluptatibus laborum? Dolor, iste! Deserunt, incidunt quas! Facilis harum quibusdam earum.
        Iste, nobis! Maiores perferendis accusamus ratione, fugiat in a consectetur dignissimos cupiditate corporis officia quidem molestias delectus soluta cumque eligendi pariatur dolor ut nam saepe atque rerum labore itaque dolorem.
        Deserunt, magnam harum doloribus provident architecto veniam odit sunt minus quod minima voluptas similique voluptates quasi! Dicta magni placeat facilis eum, atque aspernatur fugiat officiis esse nostrum deleniti quam dolore!
        Accusamus ut accusantium at quaerat quo necessitatibus perferendis fuga ex cupiditate molestiae quos error dolore dolor rem quod vel, sapiente amet dolorum alias? Totam debitis sit accusantium quam doloremque tempora?
        Ex asperiores voluptas sint nemo consequuntur! Voluptates non facilis impedit veniam fuga voluptas unde, ut maiores voluptatum nulla sint maxime ipsum vitae omnis eum quia minima quisquam reiciendis vel officiis!
        Cupiditate, architecto excepturi nihil provident accusamus obcaecati illum! Sed non recusandae nisi accusamus, esse aliquam iusto necessitatibus cumque magni facilis? Natus omnis non hic incidunt animi, necessitatibus consequatur itaque cum.
        Tempora possimus quod ea vitae dolorum doloremque repudiandae quibusdam repellendus quos odio, in esse nam architecto ducimus error nulla impedit laboriosam voluptas, veniam iste, maxime quia quidem. Rerum, accusamus ratione.
        Molestiae, impedit fugit. Corrupti, cupiditate ipsam. Repellendus numquam accusamus blanditiis unde laudantium doloremque asperiores soluta suscipit fuga. Itaque, nulla voluptates, magni, vero tempora aspernatur earum ullam dolore recusandae repellat natus.
        Maiores qui odit, in facere explicabo fugit cum sit veritatis tempora reprehenderit pariatur fugiat sequi temporibus excepturi nostrum, deleniti eligendi quibusdam accusamus debitis doloribus adipisci soluta perferendis? Iusto, eos quaerat!
        Unde, nobis consequatur optio aliquam voluptatibus distinctio autem fugit nihil explicabo aperiam, quos inventore! Recusandae, praesentium. Beatae repudiandae optio ut natus porro quia, enim voluptas quaerat incidunt, libero, velit minus.
        A pariatur iusto dicta quas accusantium porro necessitatibus eum, labore consequuntur velit, doloremque ea? Quas earum id laborum ab saepe ex, nemo doloremque deserunt voluptatibus minus dignissimos fugit nam nulla!
        Tenetur iste dicta tempora aliquid! Quisquam dolores reprehenderit repellendus, eum nobis amet beatae rerum quis veritatis minus veniam cumque nihil tempora atque quam, repudiandae quo hic. Dolore fugiat magni nulla?
        Nobis quo ea eveniet laudantium sint impedit cum tempore ad et debitis consectetur maiores provident, dolor ullam consequuntur vero quaerat assumenda est non iusto, eligendi esse dolores molestiae porro! Repudiandae.
        Tenetur voluptates, tempora blanditiis nemo dolorum quibusdam. Natus perspiciatis quaerat deleniti est eligendi facilis quam, iure consequatur nemo excepturi delectus hic officia nostrum dolores culpa porro nihil quisquam explicabo ex?
        Eaque aut autem natus mollitia dolorem optio ea incidunt aliquam molestias? Est reiciendis rem et, dignissimos accusantium hic labore aperiam nobis, maiores molestias provident sequi maxime nisi doloremque nostrum blanditiis.
        Iusto laudantium neque eum recusandae, nulla tempore quibusdam exercitationem perferendis, praesentium, a quos amet molestiae eaque. Nihil voluptate qui eos ducimus quod, inventore dolor sequi neque iste, corrupti ut! Obcaecati!
        Deleniti soluta itaque adipisci amet quia suscipit fugiat, reprehenderit nobis atque cupiditate ducimus debitis modi dolor voluptatum corrupti veniam sunt explicabo dicta officiis optio quidem repellat. Molestias unde cumque quae.
        Aliquid iste, fugiat dolores ex sequi ab commodi voluptatibus harum similique nesciunt tempora fugit vel voluptates perspiciatis est doloremque eum ipsum, praesentium ullam omnis facere! Soluta qui omnis quam ipsa.
        Itaque, molestias fuga optio numquam consequatur necessitatibus tenetur assumenda enim magni et officiis quidem odio, reiciendis voluptates consequuntur cupiditate dolorem ratione excepturi, eligendi pariatur atque. Magni exercitationem iure dignissimos explicabo?
        Illo, error magnam! Laudantium non tenetur veniam nemo harum quod qui illum molestiae est ratione mollitia, odit dolore fugit nam autem consectetur incidunt obcaecati voluptates soluta accusantium doloribus rerum quam.
        Laboriosam distinctio iste perferendis a quis accusantium nam, facere, necessitatibus repudiandae asperiores ducimus fuga accusamus pariatur earum. Asperiores dolores recusandae perspiciatis voluptatem aspernatur, earum iste consequuntur nihil, illo id labore.
        Officiis, sed cum vero molestiae aut, qui molestias, odit voluptates ducimus fuga aliquid et deleniti quam voluptatem nam repudiandae inventore totam. Impedit velit amet aliquid labore eligendi numquam ea quia!
        Earum odio porro sapiente! Laudantium a incidunt sunt impedit nobis doloribus nam, officia, culpa possimus dolorum modi, similique dolorem quo? Perspiciatis culpa consectetur explicabo aperiam animi asperiores provident natus error!
        Temporibus, eos. Architecto modi hic at ut impedit odio dolorum, est non repudiandae a harum nemo iusto atque eos qui veniam debitis ullam, corrupti delectus porro optio fugit et! Suscipit.
        Totam cum perspiciatis sed enim fugiat sequi pariatur corrupti ipsa tenetur ad quaerat odit nulla neque aspernatur necessitatibus vitae, tempore optio expedita minus modi harum dolor. Commodi ipsam ea culpa."
      />
    </Fragment>
  );
}
